### ISSUE TITLE
Running the container results in error

### ISSUE THREAD

**Issue by cmdrogogov** [ricardbejarano/dnsmasq#3]
OS: Various flavors of Fedora, tried on CoreOS also.
utilizing Podman  4.5.0
Error is persistent across several different machines, unlikely to be hw issue.

Running the container with the following command:

`podman run --name dnsmasq -p 53:53 -v /etc/dnsmasq.conf:/etc/dnsmasq.conf ricardbejarano/dnsmasq`

Produces the following error:

dnsmasq: cannot open or create lease file /var/lib/misc/dnsmasq.leases: Permission denied

It is not an SELinux issue, as that has been temporarily set to permissive, and it's not a permissions issue either.

I've also attempted using something like 

`-v /homedir/user/dnsmasq.leases:/var/lib/misc/dnsmasq.leases:z`

To map the file directly, but I get the same error.

**Comment by ricardbejarano** [comment]
What are the contents of the `dnsmasq.conf` file?

**Comment by ricardbejarano** [comment]
Closing as stale.
